### PR TITLE
Added Team Asset Folder

### PR DESCRIPTION
**Pull request by kjb336**
image

### CODE REVIEW

**Comment by twitnithegirl** [comment]
This looks amazing!

**Comment by kjb336** [comment]
Thanks @britnia .  I created a separate repo for the assets. We can remove these from this one if it would make more sense

**Comment by twitnithegirl** [comment]
whichever you think is better

**Comment by twitnithegirl** [comment]
i think we should keep the assets that we would reuse for different projects in their own repo but the ones that are specifically for this project in this repo

**Comment by kjb336** [comment]
OK.

On Thu, Aug 27, 2015 at 10:36 PM, Britni Alexander <notifications@github.com

**Comment by stephjane** [comment]
@kjb336 This looks so so good! I love it!

**Comment by AnithaPal** [comment]
@kjb336 It looks cool. Great work!!!

**Pull request merged**
