### PR TITLE
created landing page and installed bootstrap

### PR DESCRIPTION
**Pull request by twitnithegirl**
I created the landing page which will become the dashboard.
I also installed bootstrap to the application. I created a file called "additional.scss where we can add additional styles that bootstrap doesnt offer. these need to be in the Sassy CSS style.

If anyone needs information on hw to use bootstrap on their individual pages they can refer to http://getbootstrap.com/components/
After you pull the changes to your local machine localhost:3000 should now be a landing page that says "Gem and the Rubygrams" if it doesn't do 

> rake routes

then restart your server

### CODE REVIEW

**Comment by KyFaSt** [comment]
sometimes, but not always when I add something like a view I add a screenshot to make it easier for the reviewer to accept or reject changes.

@kjb336 & @nitsirk have been pretty active on the project lately, maybe one or both of them want to review this pull request?

**Comment by twitnithegirl** [comment]
Good call Kylie,

Here is a screenshot of the landing page I am talking about:
screenshot from 2015-09-02 12 19 31

**Comment by sunsplat** [comment]
Thanks Britni!

**Comment by nitsirk** [comment]
Hey @britnia, this looks good to me.  I'll merge it.

I love emojis, so here's a :tropical_fish: for you!

**Comment by twitnithegirl** [comment]
Thanks! I didn't even know tropical fish was an option.

**Comment by nitsirk** [comment]
There are so many that I have to use a [cheat sheet](http://www.emoji-cheat-sheet.com/).

**Pull request merged**
